# Generated by Django 4.2.1 on 2023-05-21 09:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_cancellation_before', models.DateTimeField(blank=True, null=True)),
                ('free_cancellation_possible', models.BooleanField(default=False)),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cityId', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('city', 'City'), ('place', 'Place')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photos', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('limit', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal', models.CharField(max_length=255)),
                ('cancellation_policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='api.cancellationpolicy')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('is_favorite', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photos', models.CharField(max_length=1000)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('count_reviews', models.PositiveIntegerField()),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('check_in_time', models.CharField(max_length=10)),
                ('check_out_time', models.CharField(max_length=10)),
                ('cityName', models.CharField(max_length=255)),
                ('cityId', models.PositiveIntegerField()),
                ('cityTimezone', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.ManyToManyField(to='api.room')),
            ],
        ),
    ]
