# Generated by Django 4.2.1 on 2023-05-21 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hotel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='children_limit',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
