# Generated by Django 4.2.1 on 2023-05-24 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='count_reviews',
        ),
        migrations.RemoveField(
            model_name='place',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='place',
            name='rating',
        ),
        migrations.AlterField(
            model_name='place',
            name='stars',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
