# Generated by Django 4.2.1 on 2023-05-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_place_count_reviews_remove_place_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='places', to='api.tag'),
        ),
    ]
