# Generated by Django 4.2.1 on 2023-05-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_tag_place_place_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_favorite',
        ),
    ]
