# Generated by Django 4.2.1 on 2023-06-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(related_name='rooms', to='api.amenity'),
        ),
    ]
