# Generated by Django 4.2.1 on 2023-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_amenity_room_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='type',
            field=models.CharField(default='Test', max_length=255),
        ),
    ]
