# Generated by Django 4.2.1 on 2023-06-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_amenity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
