# Generated by Django 4.2.1 on 2023-06-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_amenity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='baths',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='community',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='minStay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
