# Generated by Django 4.2.1 on 2023-06-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_place_baths_place_bedrooms_place_community_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='cancellation_policy',
        ),
        migrations.AddField(
            model_name='place',
            name='cancellation_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CancellationPolicy',
        ),
    ]
